# Generated by Django 4.2 on 2024-09-02 11:54

from django.db import migrations, models
import products.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(verbose_name='Штрих-код')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('volume', models.IntegerField(verbose_name='Объём')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('price_less_200', models.FloatField(verbose_name='Цена до 200 тыс. рублей')),
                ('price_more_200', models.FloatField(verbose_name='Цена от 200 тыс. рублей')),
                ('price_more_500', models.FloatField(verbose_name='Цена от 500 тыс. рублей')),
                ('is_stock', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=products.services.upload_to, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
